### ISSUE TITLE
White Border around Lesson Page Plus Badge

### ISSUE THREAD

**Issue by lupomikti** [justinikeako/darklingo#2]
For Duolingo Plus users, there is a white border around the blue Plus badge on the Lesson page (see image). It just needs to be updated to the same color as the selected theme background color.

The relevant CSS for this element is currently:
```css
._2S3SA {
    background: #fff;
    border: 3px solid #fff;
    border-radius: 8px;
    display: block;
}
```

![Screenshot of Duolingo course lesson page with Darklingo++ Slate theme showing a white-bordered, blue Plus badge near upper right corner](https://user-images.githubusercontent.com/25500382/94357232-db7ece80-004b-11eb-8056-73e50a2f334a.png)
